/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.JOptionPane;


/**
 *
 * @author JOSE
 */
public class AHome extends javax.swing.JFrame {

    /**
     * Creates new form AHome
     */
    public AHome() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        jlnombre = new javax.swing.JLabel();
        jlcontraseña = new javax.swing.JLabel();
        txtnombrelogin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pswcontraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btniniciarsesion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(0, 128, 128));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlnombre.setBackground(new java.awt.Color(102, 102, 102));
        jlnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlnombre.setForeground(new java.awt.Color(204, 204, 204));
        jlnombre.setText("Nombre:");
        Login.add(jlnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jlcontraseña.setBackground(new java.awt.Color(57, 113, 117));
        jlcontraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlcontraseña.setForeground(new java.awt.Color(204, 204, 204));
        jlcontraseña.setText("Contraseña:");
        Login.add(jlcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txtnombrelogin.setBackground(new java.awt.Color(0, 128, 128));
        txtnombrelogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnombrelogin.setForeground(new java.awt.Color(255, 255, 255));
        txtnombrelogin.setBorder(null);
        txtnombrelogin.setCaretColor(new java.awt.Color(255, 255, 255));
        Login.add(txtnombrelogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 330, 20));
        Login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 330, -1));
        Login.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, -1));

        pswcontraseña.setBackground(new java.awt.Color(0, 128, 128));
        pswcontraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pswcontraseña.setForeground(new java.awt.Color(255, 255, 255));
        pswcontraseña.setText("jPasswordField1");
        pswcontraseña.setBorder(null);
        Login.add(pswcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 330, 20));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("No estás Registrado?");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        btniniciarsesion.setBackground(new java.awt.Color(135, 206, 235));
        btniniciarsesion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btniniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        btniniciarsesion.setText("Iniciar Sesión");
        btniniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarsesionActionPerformed(evt);
            }
        });
        Login.add(btniniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 250, 40));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 450, 500));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btniniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarsesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btniniciarsesionActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       if(JOptionPane.showConfirmDialog(null, "¿Es un nuevo usuario en el sistema?", 
                "Confirmar", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
         
           RegistroNuevo r = new RegistroNuevo();
           r.setVisible(true);
           r.requestFocus();
           this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JButton btniniciarsesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlcontraseña;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JPasswordField pswcontraseña;
    private javax.swing.JTextField txtnombrelogin;
    // End of variables declaration//GEN-END:variables
}
