/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Validacion;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSE
 */
public class RegistroGrupo extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroGrupo
     */
    Validacion v;
    public RegistroGrupo() {
        initComponents();
        v=new Validacion();
    }
    
    //variables
       int cod;
       String nombregrupo;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcodgrupo = new javax.swing.JTextField();
        txtnombregrupo = new javax.swing.JTextField();
        btnRegistrarNuevo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código Del grupo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setText("Nombre del Grupo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtcodgrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodgrupoActionPerformed(evt);
            }
        });
        jPanel1.add(txtcodgrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 33, 30));

        txtnombregrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombregrupoActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombregrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 127, -1));

        btnRegistrarNuevo.setText("Registrar Nuevo Grupo");
        btnRegistrarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombregrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombregrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombregrupoActionPerformed

    private void btnRegistrarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNuevoActionPerformed
        if(v.camposvaciosrg(txtcodgrupo, txtnombregrupo))
        {
            JOptionPane.showMessageDialog(rootPane, "Hay campos en blanco", "", JOptionPane.INFORMATION_MESSAGE);
        }else
        {
            cod= Integer.parseInt(txtcodgrupo.getText());
            nombregrupo =txtnombregrupo.getText();
            JOptionPane.showMessageDialog(rootPane, "SUS DATOS HAN SIDO GUARDADOS SACTISFACTORIAMENTE", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarNuevoActionPerformed

    private void txtcodgrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodgrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodgrupoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcodgrupo;
    private javax.swing.JTextField txtnombregrupo;
    // End of variables declaration//GEN-END:variables
}
