/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Validacion;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOSE
 */
public class RegistroPersonas extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroPersonas
     */
    Validacion v;
    DefaultTableModel mtabla;//se crea una varible 
    Object data [] []={}; //donde se alamacenaran se almacenaran las filas
    String cabeza[] ={"Grupo al que pertenece","Nombres", "Apellidos","Celular","Teléfono","Sexo"};//nombres de las columnas
    public RegistroPersonas() {
        initComponents();
        v=new Validacion();
        mtabla= new DefaultTableModel(data,cabeza );
        jttabladatos.setModel(mtabla);//le manda el modelo anteriormente creado
    }

   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbF = new javax.swing.JRadioButton();
        rbM = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jttabladatos = new javax.swing.JTable();
        btnsalir = new org.edisoncor.gui.button.ButtonAction();
        btnregistrar = new org.edisoncor.gui.button.ButtonAction();
        jLabel1 = new javax.swing.JLabel();
        cbogrupos = new javax.swing.JComboBox<>();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Celular:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, -1));

        txtnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombresActionPerformed(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 210, -1));

        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });
        getContentPane().add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 210, -1));

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 210, -1));

        txtcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcelularActionPerformed(evt);
            }
        });
        txtcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcelularKeyTyped(evt);
            }
        });
        getContentPane().add(txtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Sexo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        buttonGroup1.add(rbF);
        rbF.setText("F");
        rbF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFActionPerformed(evt);
            }
        });
        getContentPane().add(rbF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        buttonGroup1.add(rbM);
        rbM.setText("M");
        getContentPane().add(rbM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jttabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Grupo al que pertenece", "Nombre", "Apellido", "Celular", "Teléfono", "Sexo"
            }
        ));
        jScrollPane1.setViewportView(jttabladatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 840, 150));

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Grupo al cual pertenece:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        cbogrupos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRUPO DE CATEQUESIS", "CONSEJO DE PASTORAL", "CONSEJO DE PASTORAL", "GRUPO DE MONAGUILLOS", "VISITADORES DE ENFERMOS", "GRUPO DE JÓVENES", "GRUPO DE ADULTOS", "GRUPO DE LECTORES", "MINISTROS DE LA COMUNIÓN" }));
        getContentPane().add(cbogrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombresActionPerformed

    }//GEN-LAST:event_txtnombresActionPerformed

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        v.solotexto(evt.getKeyChar(),evt);
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        v.solotexto(evt.getKeyChar(),evt);
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        v.solonumeros(evt.getKeyChar(),evt);//llama al método solotexto para  validar que el usuario solo ingrese números.
        if(txttelefono.getText().length()>=7)
        {
            evt.consume();
            //JOptionPane.showMessageDialog(rootPane, "Sólo se permiten siete caracteres");
        }//finsi
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcelularActionPerformed

    private void txtcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularKeyTyped
        v.solonumeros(evt.getKeyChar(),evt);
        if(txtcelular.getText().length()>=10)
        {
            evt.consume();
            //JOptionPane.showMessageDialog(rootPane, "Sólo se permiten siete caracteres");
        }//finsi
    }//GEN-LAST:event_txtcelularKeyTyped

    private void rbFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed

        if(v.camposenblancoRP(txtnombres, txtapellidos, txtcelular,txttelefono))
        {
            JOptionPane.showMessageDialog(rootPane, "Por favor complete los espacios en blanco", "ERROR AL REGISTRAR", JOptionPane.ERROR_MESSAGE);

        }
        else
        {
            if(v.catidaddedigitostel(txttelefono))//validad la cantidad de digitos del teléfono
                {
                    JOptionPane.showMessageDialog(rootPane, "El Teléfono debe tener ocho digitos","ERROR AL REGISTRAR",JOptionPane.ERROR_MESSAGE);
                    txttelefono.setText("");

                }else
                    {
                            if(!v.validarcel(txtcelular))//validad la cantidad de digitos del celuar
                            {
                                JOptionPane.showMessageDialog(rootPane, "El Celular debe tener diez digitos","ERROR AL REGISTRAR",JOptionPane.ERROR_MESSAGE);
                                txtcelular.setText("");

                            }else
                            {
                                 if(!v.validarsexo(rbM, rbF))//valida que si eligio una opción
                                {
                                    JOptionPane.showMessageDialog(rootPane, "Por favor seleccione una OPCIÓN en SEXO",
                                        "Seleccione Sexo", JOptionPane.WARNING_MESSAGE);
                                }
                                else
                                  {
                                        if(JOptionPane.showConfirmDialog(rootPane, "¿Està seguro de Registrar los Datos?",
                                            "Confirmaciòn", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
                                        {
                                        //guardar los datos
                                       Object grupo=cbogrupos.getSelectedItem();//selecciona el dato que que está en el combobox
                                        v.setNom(txtnombres.getText());
                                        v.setApel(txtapellidos.getText());
                                        //guardar fecha
                                        //String fecha=v.fecha(dchfechanacimiento);
                                        //v.setCorreo(txtcorreo.getText());
                                        v.setCel(txtcelular.getText());
                                        v.setTel(txttelefono.getText());
                                        //Guarda opcción de sexo
                                        if(rbM.isSelected())
                                        {
                                            v.setSexo("M");
                                        }else{v.setSexo("F");}
                                        //manda los datos a la tabla
                                        Object datos[]={grupo,v.getNom(),v.getApel(),v.getCel(),v.getTel(),v.getSexo()};
                                        mtabla.addRow(datos);// añadir las filas donde se le almacenaronlos datos anteriormente
                                        //limpia los datos
                                        
                                        this.txtnombres.setText("");
                                        this.txtapellidos.setText("");
                                        this.txtcelular.setText("");
                                        this.txttelefono.setText("");
                                        rbF.remove(rbF);
                                        rbM.remove(rbM);
                                        
                                        JOptionPane.showMessageDialog(rootPane, "Ha sido registrado en la plataforma satisfactoriamente",
                                            "Acción Correcta", JOptionPane.INFORMATION_MESSAGE);
                                        }
                                  }
                            }
                 }
        }//finsi
        

    }//GEN-LAST:event_btnregistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction btnregistrar;
    private org.edisoncor.gui.button.ButtonAction btnsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbogrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jttabladatos;
    private javax.swing.JRadioButton rbF;
    private javax.swing.JRadioButton rbM;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
