/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author JOSE
 */
public class RegistroCursos extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroCursos
     */
    public RegistroCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombrecurso = new javax.swing.JTextField();
        txtnumcurso = new javax.swing.JTextField();
        txtdiainicio = new javax.swing.JTextField();
        txtdescipcion = new javax.swing.JTextField();
        Btnguardarcurso = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbopublico = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Número del Curso:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setText("Nombre del Curso:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setText("Día de inicio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setText("Descripción");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtnombrecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrecursoActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombrecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 210, -1));
        jPanel1.add(txtnumcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 50, -1));

        txtdiainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiainicioActionPerformed(evt);
            }
        });
        jPanel1.add(txtdiainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 80, -1));

        txtdescipcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescipcionActionPerformed(evt);
            }
        });
        jPanel1.add(txtdescipcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 210, 110));

        Btnguardarcurso.setText("Registrar");
        Btnguardarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnguardarcursoActionPerformed(evt);
            }
        });
        jPanel1.add(Btnguardarcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel5.setText("Público dirigido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        cbopublico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sleccione Público", "Todos", "Niños", "Jóvenes", "Adultos", "Casados" }));
        jPanel1.add(cbopublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Bíblico", "Todos", "Curso donde conoceran más a "},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número del Curso", "Nombre del Curso", "Público Dirigido", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, 291));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombrecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecursoActionPerformed

    private void txtdiainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiainicioActionPerformed

    private void txtdescipcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescipcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescipcionActionPerformed

    private void BtnguardarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnguardarcursoActionPerformed
        
        
    }//GEN-LAST:event_BtnguardarcursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnguardarcurso;
    private javax.swing.JComboBox<String> cbopublico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtdescipcion;
    private javax.swing.JTextField txtdiainicio;
    private javax.swing.JTextField txtnombrecurso;
    private javax.swing.JTextField txtnumcurso;
    // End of variables declaration//GEN-END:variables
}
