/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Validacion;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSE
 */
public class RegistroParroco extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroParroco
     */
    Validacion v;
    public RegistroParroco() {
        initComponents();
        v =new Validacion();
        //this.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlidentificacion = new javax.swing.JLabel();
        jlnombre = new javax.swing.JLabel();
        jlapelldio = new javax.swing.JLabel();
        jlfchanaci = new javax.swing.JLabel();
        jbcorreo = new javax.swing.JLabel();
        jlcorreo = new javax.swing.JLabel();
        txtidentificacion = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        dchfechanacimiento = new com.toedter.calendar.JDateChooser();
        txtcorreo = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        btnregistrar = new org.edisoncor.gui.button.ButtonAction();
        btnsalir = new org.edisoncor.gui.button.ButtonAction();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Registro Nuevo Parroco");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlidentificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlidentificacion.setText("Identificación:");
        jPanel1.add(jlidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 100, -1, -1));

        jlnombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlnombre.setText("Nombres:");
        jPanel1.add(jlnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 131, -1, -1));

        jlapelldio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlapelldio.setText("Apelidos:");
        jPanel1.add(jlapelldio, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 169, -1, -1));

        jlfchanaci.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlfchanaci.setText("Fecha de Nacimiento:");
        jPanel1.add(jlfchanaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 210, -1, -1));

        jbcorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbcorreo.setText("Correo:");
        jPanel1.add(jbcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 245, -1, -1));

        jlcorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlcorreo.setText("Celular:");
        jPanel1.add(jlcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 286, -1, -1));

        txtidentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 100, 165, -1));

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 131, 165, -1));

        txtapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidosActionPerformed(evt);
            }
        });
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });
        jPanel1.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 169, 165, -1));
        jPanel1.add(dchfechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 207, 165, -1));

        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcorreoKeyTyped(evt);
            }
        });
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 245, 165, -1));

        txtcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcelularKeyTyped(evt);
            }
        });
        jPanel1.add(txtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 286, 165, -1));

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 400, 91, -1));

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 400, 85, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 430, 490));

        setBounds(0, 0, 472, 562);
    }// </editor-fold>//GEN-END:initComponents

    private void txtapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidosActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        
        if(v.camposenblancorp(txtidentificacion, txtnombre, txtapellidos, txtcelular, txtcorreo))
        {
                JOptionPane.showMessageDialog(rootPane, "Por favor complete los espacios en blanco", "ERROR AL REGISTRAR", JOptionPane.ERROR_MESSAGE);

        }
        else
           {
               if(v.cantidaddedigitosid(txtidentificacion))
               {
                        JOptionPane.showMessageDialog(rootPane, "Le identificación debe contener diez digitos ","ERROR AL REGISTRAR",JOptionPane.ERROR_MESSAGE);
                        txtidentificacion.setText("");
               }
                else
                   {
                        if(!v.validarcel(txtcelular))//validad la cantidad de digitos del celular
                        {
                                JOptionPane.showMessageDialog(rootPane, "El Celular debe tener diez digitos","ERROR AL REGISTRAR",JOptionPane.ERROR_MESSAGE);
                                txtcelular.setText("");


                        }else
                            {
                                if(JOptionPane.showConfirmDialog(rootPane, "¿Està seguro de Registrar los Datos?", 
                                        "Confirmaciòn", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
                                {
                                //guardar los datos
                                v.setIdenti(txtidentificacion.getText());
                                v.setNom(txtnombre.getText());
                                v.setApel(txtapellidos.getText());
                                //guardar fecha
                                String fecha=v.fecha(dchfechanacimiento);
                                v.setCorreo(txtcorreo.getText());
                                v.setCel(txtcelular.getText());
                                JOptionPane.showMessageDialog(rootPane, "Ha sido registrado en la plataforma satisfactoriamente",
                                    "Acción Correcta", JOptionPane.INFORMATION_MESSAGE);
                                }
                            }
                   }//finsi   
            }
        
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void txtcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyTyped
        if(v.isEmail(txtcorreo))
          {
              JOptionPane.showMessageDialog(rootPane, "Imail incorrecto", "Email", JOptionPane.ERROR);
              txtcorreo.requestFocus();
          }
    }//GEN-LAST:event_txtcorreoKeyTyped

    private void txtcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularKeyTyped
        v.solonumeros(evt.getKeyChar(),evt);//llama al método solotexto para  validar que el usuario solo ingrese números.
        if( txtcelular.getText().length()>=10)
        {
            evt.consume();
            //JOptionPane.showMessageDialog(rootPane, "Sólo se permiten de ocho a diez caracteres");
        }//finsi
    }//GEN-LAST:event_txtcelularKeyTyped

    private void txtidentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidentificacionKeyTyped
        v.solonumeros(evt.getKeyChar(),evt);//llama al método solotexto para  validar que el usuario solo ingrese números.
        if( txtidentificacion.getText().length()>=10)
        {
            evt.consume();
            //JOptionPane.showMessageDialog(rootPane, "Sólo se permiten de ocho a diez caracteres");
        }//finsi
    }//GEN-LAST:event_txtidentificacionKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
       v.solotexto(evt.getKeyChar(),evt);
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
         v.solotexto(evt.getKeyChar(),evt);
    }//GEN-LAST:event_txtapellidosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction btnregistrar;
    private org.edisoncor.gui.button.ButtonAction btnsalir;
    private com.toedter.calendar.JDateChooser dchfechanacimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jbcorreo;
    private javax.swing.JLabel jlapelldio;
    private javax.swing.JLabel jlcorreo;
    private javax.swing.JLabel jlfchanaci;
    private javax.swing.JLabel jlidentificacion;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtidentificacion;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
